name: rag-agent
channels:
  - conda-forge
dependencies:
  - python=3.10
  - python-dotenv==1.0.1
  - streamlit==1.40.1
  - wikipedia==1.4.0
  - arxiv==2.1.3
  - pytest
  - pip
  - pip:
      - langchain-core==0.3.21
      - langchain-community==0.3.8
      - langchain-huggingface==0.1.2
      - faiss-cpu==1.9.0.post1
      - langchain-google-genai==2.0.5
