name: Build Conda Environment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Miniconda
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          environment-file: environment.yml
          activate-environment: rag-agent
          
      # Create .env file with secrets
      - name: Create .env file
        run: |
          echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" >> .env
          echo "LANGCHAIN_API_KEY=${{ secrets.LANGCHAIN_API_KEY }}" >> .env
          echo "HUGGINGFACE_TOKEN=${{ secrets.HUGGINGFACE_TOKEN }}" >> .env
          
      # Verify Conda environment
      - name: Check installed packages
        run: |
          source $(conda info --base)/etc/profile.d/conda.sh
          conda activate rag-agent
          which python
          python --version
          conda list
        
      - name: Run tests
        run: |
          source $(conda info --base)/etc/profile.d/conda.sh
          conda activate rag-agent
          pytest tests/
